site_name: 'example-docs'

nav:
  - Home: index.md
  - Cars: cars.md
  - Electric Guitars: electric-guitars.md
  - Chinese Food: chinese-food.md
  - Greeting: hello/hello.md

plugins:
  - techdocs-core
