site_name: 'example-docs'

nav:
  - Home: index.md
  - Home/Cars: cars.md
  - Home/Electric Guitars: electric-guitars.md
  - Home/Chinese Food: chinese-food.md
  - Home/Old Hollywood: intro.md
  - Home/Old Hollywood: Grace-Kelly.md
  - Home/Old Hollywood: Fred-Astaire.md
  - Home/Old Hollywood: Audrey-Hepburn.md

plugins:
  - techdocs-core
