site_name: 'example-docs'

nav:
  - Home: index.md
  - Home/Cars: cars.md
  - Home/Electric Guitars: electric-guitars.md
  - Home/Chinese Food: chinese-food.md
  - Home/Old Hollywood/Intro: intro.md
  - Home/Old Hollywood/Grace Kelly Films: Grace-Kelly.md

plugins:
  - techdocs-core
